In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
# using empty
torch.empty(2,3)

tensor([[1.0430e-08, 8.5381e-07, 2.1707e-18],
        [4.5447e+30, 7.0062e+22, 2.1715e-18]])

In [ ]:
a = torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
a

tensor([[7.2455e-34, 0.0000e+00, 7.1210e-34],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
# using zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(3,4)

tensor([[0.7177, 0.9146, 0.8066, 0.0989],
        [0.4594, 0.7603, 0.8093, 0.2836],
        [0.7600, 0.2592, 0.4462, 0.4340]])

In [ ]:
# use of seed
torch.manual_seed(50)
torch.rand(3,4)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])

In [ ]:
torch.manual_seed(50)
torch.rand(3,4)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])

In [ ]:
# using tensor
torch.tensor([[2,3,4], [5,7,4]])

tensor([[2, 3, 4],
        [5, 7, 4]])

In [ ]:
# other ways
# arrange
print("arange ->", torch.arange(1, 10, 2))
# using linspace
print("linspace ->", torch.linspace(0, 10, 10))
# using eye
print("eye ->", torch.eye(3))
# using full
print("full ->", torch.full((3,2),5))

arange -> tensor([1, 3, 5, 7, 9])
linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
full -> tensor([[5, 5],
        [5, 5],
        [5, 5]])


## Tensor shapes

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[135139253230976,       157300224,            1122],
        [              0,            2183,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.9879, 0.8389, 0.5791],
        [0.8991, 0.7164, 0.4144]], dtype=torch.float64)

## Tensor Datatype

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign datatype
torch.tensor([1.0,2.0,3.0], dtype=torch.int64)

tensor([1, 2, 3])

In [ ]:
torch.tensor([1,2,3,4,5], dtype=torch.float64)

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# using to
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

## Mathmatical operation

### 1. scaler operation

In [ ]:
x = torch.rand(2,3)

In [ ]:
x

tensor([[0.2792, 0.2526, 0.3792],
        [0.7686, 0.6907, 0.7526]])

In [ ]:
# addition
x+3

tensor([[3.2792, 3.2526, 3.3792],
        [3.7686, 3.6907, 3.7526]])

In [ ]:
# substraction
x-3

tensor([[-2.7208, -2.7474, -2.6208],
        [-2.2314, -2.3093, -2.2474]])

In [ ]:
# multiplication
x*2

tensor([[0.5585, 0.5052, 0.7584],
        [1.5372, 1.3814, 1.5053]])

In [ ]:
# division
x/2

tensor([[0.1396, 0.1263, 0.1896],
        [0.3843, 0.3454, 0.3763]])

In [ ]:
# int diviation
(x*10)//2

tensor([[1., 1., 1.],
        [3., 3., 3.]])

In [ ]:
# mod
((x*10)//2)%5

tensor([[1., 1., 1.],
        [3., 3., 3.]])

In [ ]:
# power
x**2

tensor([[0.0780, 0.0638, 0.1438],
        [0.5907, 0.4771, 0.5665]])

### 2. Eliment wise operation

In [ ]:
a = torch.rand(2,4)
b = torch.rand(2,4)

In [ ]:
a

tensor([[0.5680, 0.5034, 0.2074, 0.4779],
        [0.4203, 0.4014, 0.0436, 0.6490]])

In [ ]:
b

tensor([[0.9007, 0.8274, 0.3785, 0.7518],
        [0.2839, 0.7220, 0.8421, 0.2474]])

In [ ]:
# addition
a+b

tensor([[1.4687, 1.3308, 0.5859, 1.2296],
        [0.7042, 1.1234, 0.8857, 0.8965]])

In [ ]:
# substraction
a-b

tensor([[-0.3326, -0.3240, -0.1711, -0.2739],
        [ 0.1364, -0.3205, -0.7985,  0.4016]])

In [ ]:
# multiplication
a*b

tensor([[0.5116, 0.4165, 0.0785, 0.3592],
        [0.1193, 0.2898, 0.0367, 0.1606]])

In [ ]:
# division
a/b

tensor([[0.6307, 0.6084, 0.5480, 0.6356],
        [1.4805, 0.5560, 0.0518, 2.6231]])

In [ ]:
# power
a**b

tensor([[0.6009, 0.5667, 0.5514, 0.5740],
        [0.7819, 0.5174, 0.0715, 0.8986]])

In [ ]:
# mod
a % b

tensor([[0.5680, 0.5034, 0.2074, 0.4779],
        [0.1364, 0.4014, 0.0436, 0.1542]])

In [ ]:
c = torch.tensor([1,-3,4,-2])

In [ ]:
# abs
torch.abs(c)

tensor([1, 3, 4, 2])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  3, -4,  2])

In [ ]:
d = torch.tensor([2.4, 3.4, 5.3, 1.2])

In [ ]:
# round
torch.round(d)

tensor([2., 3., 5., 1.])

In [ ]:
# ceil
torch.ceil(d)

tensor([3., 4., 6., 2.])

In [ ]:
# floor
torch.floor(d)

tensor([2., 3., 5., 1.])

In [ ]:
# clamp
torch.clamp(d, min=3, max=6)

tensor([3.0000, 3.4000, 5.3000, 3.0000])

### 3. reduction operation


In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float64)

In [ ]:
e

tensor([[5., 6., 5.],
        [5., 1., 9.]], dtype=torch.float64)

In [ ]:
# sum
torch.sum(e)

tensor(31., dtype=torch.float64)

In [ ]:
# sum along colums
torch.sum(e, dim=0)

tensor([10.,  7., 14.], dtype=torch.float64)

In [ ]:
# sum along rows
torch.sum(e, dim=1)

tensor([16., 15.], dtype=torch.float64)

In [ ]:
# mean
torch.mean(e)

tensor(5.1667, dtype=torch.float64)

In [ ]:
# median
torch.median(e)

tensor(5., dtype=torch.float64)

In [ ]:
# max
torch.max(e)

tensor(9., dtype=torch.float64)

In [ ]:
# min
torch.min(e)

tensor(1., dtype=torch.float64)

In [ ]:
# product
torch.prod(e)

tensor(6750., dtype=torch.float64)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.5626, dtype=torch.float64)

In [ ]:
# variance
torch.var(e)

tensor(6.5667, dtype=torch.float64)

In [ ]:
# argmax
torch.argmax(e)

tensor(5)

In [ ]:
# argmin
torch.argmin(e)

tensor(4)

### 4. Matrix operation

In [ ]:
p = torch.randint(size=(2,3), low=0, high=20)
q = torch.randint(size=(3,2), low=0, high=20)

In [ ]:
p

tensor([[ 9,  2, 11],
        [ 2,  6,  8]])

In [ ]:
q

tensor([[ 2,  9],
        [ 6,  7],
        [19,  0]])

In [ ]:
# matrix multiplication
torch.matmul(p,q)

tensor([[239,  95],
        [192,  60]])

In [ ]:
import torch

In [ ]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

In [ ]:
vector1

tensor([1, 2, 3])

In [ ]:
# dot product
torch.dot(vector1, vector2)

tensor(32)

In [ ]:
# transpose
torch.transpose(p, 0, 1)

tensor([[ 9,  2],
        [ 2,  6],
        [11,  8]])

In [ ]:
h = torch.randint(size=(2,3), low=0, high=20, dtype=torch.float64)

In [ ]:
h

tensor([[ 2.,  0., 19.],
        [ 2.,  2.,  3.]], dtype=torch.float64)

### 5. comparison operation

In [ ]:
i = torch.randint(size=(2,3), low=0, high=20)
j = torch.randint(size=(2,3), low=0, high=20)

In [ ]:
i

tensor([[11,  4, 13],
        [16,  4, 16]])

In [ ]:
j

tensor([[18, 16,  7],
        [18, 14, 14]])

In [ ]:
# greater than
i > j

tensor([[False, False,  True],
        [False, False,  True]])

In [ ]:
# less than
i < j

tensor([[ True,  True, False],
        [ True,  True, False]])

In [ ]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# greater than equal to
i >= j

tensor([[False, False,  True],
        [False, False,  True]])

In [ ]:
# less than equal to
i <= j

tensor([[ True,  True, False],
        [ True,  True, False]])

### 6. special function

In [ ]:
k = torch.randint(size=(2,3), low=0, high=20, dtype=torch.float64)

In [ ]:
k

tensor([[15., 17.,  6.],
        [19.,  0.,  9.]], dtype=torch.float64)

In [ ]:
# log
torch.log(k)

tensor([[2.7081, 2.8332, 1.7918],
        [2.9444,   -inf, 2.1972]], dtype=torch.float64)

In [ ]:
# exp
torch.exp(k)

tensor([[3.2690e+06, 2.4155e+07, 4.0343e+02],
        [1.7848e+08, 1.0000e+00, 8.1031e+03]], dtype=torch.float64)

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[3.8730, 4.1231, 2.4495],
        [4.3589, 0.0000, 3.0000]], dtype=torch.float64)

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[1.0000, 1.0000, 0.9975],
        [1.0000, 0.5000, 0.9999]], dtype=torch.float64)

In [ ]:
# softmax
torch.softmax(k, dim=1)

tensor([[1.1920e-01, 8.8078e-01, 1.4711e-05],
        [9.9995e-01, 5.6025e-09, 4.5398e-05]], dtype=torch.float64)

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[1.7986e-02, 1.0000e+00, 4.7426e-02],
        [9.8201e-01, 4.1399e-08, 9.5257e-01]], dtype=torch.float64)

In [ ]:
# relu
torch.relu(k)

tensor([[15., 17.,  6.],
        [19.,  0.,  9.]], dtype=torch.float64)

### 7. Inplace operation

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [ ]:
m

tensor([[0.8548, 0.5334, 0.5371],
        [0.3119, 0.5796, 0.3976]])

In [ ]:
n

tensor([[0.7836, 0.2932, 0.0385],
        [0.5873, 0.9745, 0.6319]])

In [ ]:
m.add_(n)

tensor([[1.6384, 0.8266, 0.5756],
        [0.8992, 1.5541, 1.0295]])

In [ ]:
m

tensor([[1.6384, 0.8266, 0.5756],
        [0.8992, 1.5541, 1.0295]])

In [ ]:
torch.relu(m)

tensor([[1.6384, 0.8266, 0.5756],
        [0.8992, 1.5541, 1.0295]])

In [ ]:
m.relu_()

tensor([[1.6384, 0.8266, 0.5756],
        [0.8992, 1.5541, 1.0295]])

In [ ]:
m

tensor([[1.6384, 0.8266, 0.5756],
        [0.8992, 1.5541, 1.0295]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)

In [ ]:
a

tensor([[0.7101, 0.4933, 0.1724],
        [0.9825, 0.6587, 0.3278]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.7101, 0.4933, 0.1724],
        [0.9825, 0.6587, 0.3278]])

In [ ]:
a[0][0] = 2

In [ ]:
a

tensor([[2.0000, 0.4933, 0.1724],
        [0.9825, 0.6587, 0.3278]])

In [ ]:
b

tensor([[2.0000, 0.4933, 0.1724],
        [0.9825, 0.6587, 0.3278]])

In [ ]:
id(a)

132631725855120

In [ ]:
id(b)

132631725855120

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[2.0000, 0.4933, 0.1724],
        [0.9825, 0.6587, 0.3278]])

In [ ]:
id(b)

132631545107888

In [ ]:
id(a)

132631725855120

In [ ]:
a[0][0]=1

In [ ]:
a

tensor([[1.0000, 0.4933, 0.1724],
        [0.9825, 0.6587, 0.3278]])

In [ ]:
b

tensor([[2.0000, 0.4933, 0.1724],
        [0.9825, 0.6587, 0.3278]])